# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c0229b67085adda694d84990db52f97dc358f1e4ff314fc64a3f238a838481e26cb6d2ed3b7dc1d5c0d14ddd1a2f654a3b62860d0150b2821bd30aa8ae6939

test:
  secret_key_base: f00cf0bd69b11639481c3f4b6f5339add22aef1455fd2a091f550696d9aabe6d1fba96ac728fd0b9d4f2370c3aacdf24ebaca20afafe6f48abb3ca57ee84af5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
